### ISSUE TITLE
No issue - good !

### ISSUE THREAD

**Issue by biokomiker** [bassmanitram/actions-for-nautilus#5]
I made a user make install. Works smoothly.

And configured one of the actions I started to miss from Gnome 42:

![grafik](https://user-images.githubusercontent.com/20150288/181360353-79fa740e-3ebd-4a32-9839-151010197c0c.png)

The nested structure in Folder actions and Copy is very nice as well.

Georg

**Comment by bassmanitram** [comment]
VERY nice!!! I'll play with that myself!

You probably understand, but you know you can create your own nested
structures too.

Thanks

Martin

**Comment by biokomiker** [comment]
I tweaked the deja-dup a bit: It is also possible to restore a) directories and b) multiples files and directories in one rush.

{
  "type": "command",
  "label": "restore previous version",
  "command_line": "deja-dup --restore %F",
  "mimetypes": [],
  "filetypes": [
    "file",
    "directory"
  ]
},

**Comment by bassmanitram** [comment]
Thx - added to the Wiki

**Comment by JavaScriptDude** [comment]
Did not want to spam with a new issue but I just wanted to say thanks for this extension. Its something I have been looking forward to since I switched to Linux almost 10 years ago for my primary development desktops. In Windohs, I used File Menu Tools heavily and now I finally have something to fill that hole. 

Mucho Kudos!
